import type { GanttChartDefaults, RendererName } from './types'

/** Where a renderer name points: the package to import, and its factory export. */
export interface RendererTarget {
  pkg: string
  factory: string
}

/**
 * Source for the generated `#ganttkit-options` module.
 *
 * The renderer is re-exported statically rather than looked up in a table at
 * runtime, so the bundler can see that the two renderers this app did not
 * choose are unreachable and drop them. That is the whole reason the module
 * takes a renderer *name* instead of a factory: a factory in `nuxt.config`
 * could not survive the trip to the client bundle.
 *
 * `defaults` is inlined as JSON, which also drops any key left `undefined` -
 * so an option the config never mentions is absent here rather than present
 * and empty, and the component's prop default falls through to the engine's.
 */
export function optionsModuleSource(target: RendererTarget, defaults: GanttChartDefaults): string {
  return [
    '// Generated by @ganttkit/nuxt - configure via `ganttkit` in nuxt.config.',
    `export { ${target.factory} as renderer } from '${target.pkg}'`,
    '',
    `export const defaults = Object.freeze(${JSON.stringify(defaults, null, 2)})`,
    '',
  ].join('\n')
}

/**
 * Source for the matching `.d.ts`.
 *
 * Typed off the package entry rather than a path inside `dist`, so it keeps
 * resolving however the build lays the runtime out.
 */
export function optionsTypeSource(): string {
  return [
    'declare module \'#ganttkit-options\' {',
    '  type Options = import(\'@ganttkit/nuxt\').GanttKitRuntimeOptions',
    '  export const renderer: Options[\'renderer\']',
    '  export const defaults: Options[\'defaults\']',
    '}',
    '',
  ].join('\n')
}

/**
 * Every renderer this module can wire up, keyed by `ModuleOptions['renderer']`.
 *
 * Build-time only: it never reaches the bundle, because the generated module
 * names one package directly rather than importing this table.
 */
export const RENDERERS = {
  html: { pkg: '@ganttkit/html', factory: 'htmlRenderer' },
  svg: { pkg: '@ganttkit/svg', factory: 'svgRenderer' },
  canvas: { pkg: '@ganttkit/canvas', factory: 'canvasRenderer' },
} satisfies Record<RendererName, RendererTarget>

/**
 * Validate `ganttkit.prefix` and hand back the trimmed word.
 *
 * Nuxt asks modules to prefix what they inject, and this one prefix names both
 * a component and a composable - `<GanttChart>` and `useGantt()` - so an empty
 * or non-PascalCase value would produce `<Chart>` and `use()` rather than
 * something merely ugly. Rejected here, with the fix in the message, instead of
 * surfacing later as a component Nuxt cannot resolve.
 */
export function resolvePrefix(prefix: string | undefined): string {
  const resolved = (prefix ?? 'Gantt').trim()
  if (!/^[A-Z][A-Za-z0-9]*$/.test(resolved)) {
    throw new Error(
      `[@ganttkit/nuxt] prefix: ${JSON.stringify(prefix)} is not usable. `
      + `It names a component and a composable, so it has to be a non-empty `
      + `PascalCase word - 'Gantt' (the default) gives <GanttChart> and useGantt().`,
    )
  }
  return resolved
}
